
enum RequestError {
  // General error codes
  ERROR_BAD_CRC,
  ERROR_BAD_LENGTH,
  ERROR_UNKNOWN,

  //Pairing service error codes
  P_ERROR_NOT_PAIRING,
  P_ERROR_BAD_AUTHENTICATOR,
  P_ERROR_BAD_PARAMETER,
  P_ERROR_MAX_USERS_EXCEEDED,

  // Keyturner service error codes
  K_ERROR_NOT_AUTHORIZED,
  K_ERROR_BAD_PIN,
  K_ERROR_BAD_NONCE,
  K_ERROR_BAD_PARAMETER,
  K_ERROR_INVALID_AUTH_ID,
  K_ERROR_DISABLED,
  K_ERROR_REMOTE_NOT_ALLOWED,
  K_ERROR_TIME_NOT_ALLOWED,
  K_ERROR_TOO_MANY_PIN_ATTEMPTS,
  K_ERROR_TOO_MANY_ENTRIES,
  K_ERROR_CODE_ALREADY_EXISTS,
  K_ERROR_CODE_INVALID,
  K_ERROR_CODE_INVALID_TIMEOUT_1,
  K_ERROR_CODE_INVALID_TIMEOUT_2,
  K_ERROR_CODE_INVALID_TIMEOUT_3,
  K_ERROR_AUTO_UNLOCK_TOO_RECENT,
  K_ERROR_POSITION_UNKNOWN,
  K_ERROR_MOTOR_BLOCKED,
  K_ERROR_CLUTCH_FAILURE,
  K_ERROR_MOTOR_TIMEOUT,
  K_ERROR_BUSY,
  K_ERROR_CANCELED,
  K_ERROR_NOT_CALIBRATED,
  K_ERROR_MOTOR_POSITION_LIMIT,
  K_ERROR_MOTOR_LOW_VOLTAGE,
  K_ERROR_MOTOR_POWER_FAILURE,
  K_ERROR_CLUTCH_POWER_FAILURE,
  K_ERROR_VOLTAGE_TOO_LOW,
  K_ERROR_FIRMWARE_UPDATE_NEEDED,

  // API errors
  API_CRC_AUTHENTICATION_FAILED,
  API_AUTHID_AUTHENTICATION_FAILED,
  API_FAILED_TO_CALC_SSK,
  API_UNKNOWN_ERROR,

}


